### ISSUE TITLE
maybe a concurrency problem?

### ISSUE THREAD

**Issue by Summuss** [changkun/midgard#15]
When following two  statements of `m.readChs.Store(m.ID, readerCh)`  run conrrently, will any `readerCh`  be override by the other with  the same `m.Id`? If so the `readerCh` overrided won't be able to receive message. 
```go
// ListDaemons lists all active daemons.
func (m *Daemon) ListDaemons(ctx context.Context, in *proto.ListDaemonsInput) (out *proto.ListDaemonsOutput, err error) {
        //segment1
	readerCh := make(chan *types.WebsocketMessage)
	m.readChs.Store(m.ID, readerCh)
	m.writeCh <- &types.WebsocketMessage{
		Action:  types.ActionListDaemonsRequest,
		UserID:  m.ID,
		Message: "list active daemons",
	}
//.........
}
```
```go
case <-m.forceUpdate:
	log.Println("received force status updates")
        //segment2
	readerCh := make(chan *types.WebsocketMessage)
	m.readChs.Store(m.ID, readerCh)
```

**Comment by changkun** [comment]
m.ID is guaranteed to be globally unique.

**Comment by Summuss** [comment]
For one daemon instance, `m.readChs.Store(m.ID, readerCh)` in rpc service and that in watchOfficeStatus would have the same `m.ID`. Is that so?

**Comment by changkun** [comment]
Yes, I think so.

**Comment by changkun** [comment]
Are you thinking that if readerCh was overwritten then the ListDaemon, for instance, will block forever?

**Comment by Summuss** [comment]
Yes, I‘m afraid of that situation.

**Comment by changkun** [comment]
I evaluated the case, and I think you are right, a patch to fix the issue is on the way.
