### ISSUE TITLE
demon start failed in windows platform

### ISSUE THREAD

**Issue by kvii** [changkun/midgard#19]
# windows 平台 daemon 命令运行报错

windows 平台下 `mg daemon start` 运行报错。
我觉得应该是 [mg daemon start](https://github.com/changkun/midgard/blob/main/cmd/daemon.go#L56) 没有调用 s.Run 方法的原因。

## 复现步骤

1. windows 平台下执行 `make` 打包应用。
2. 执行 `./mg daemon install` 注册服务。
3. 执行 `./mg daemon start` 运行服务。
4. 一段时间后控制台报错 midgard: failed to start, err: The service did not respond to the start or control request in a timely fashion.

## 解释

个人猜测，windows 平台下服务注册与启动流程应该是这样的：

1. Install 方法将 `path/to/your/service run` 注册到系统服务中。
2. Start 方法通知系统后台执行 `path/to/your/service run` 命令。
3. 命令被系统调用后。调用 Run 方法通知系统与 Handler 交互。
4. Handler 通过 Execute 方法与系统交互。在其他协程中运行业务逻辑。

而当前的 `mg daemon run` 命令直接在当前协程运行了业务逻辑，并且没使用 s.Run 方法。
导致 Handler 无法与系统进行交互。最终超时报错。

**Comment by changkun** [comment]
应该是个 bug，对windows平台的经验不多，如果可以，直接使用 mg daemon run 来运行服务。

**Comment by kvii** [comment]
直接运行 mg daemon run 会占用当前 terminal。所以不能用这条命令运行一个后台服务。

**Comment by kvii** [comment]
> 应该是个 bug，对windows平台的经验不多，如果可以，直接使用 mg daemon run 来运行服务。

直接运行 mg daemon run 会占用当前 terminal。所以不能用这条命令运行一个后台服务。

**Comment by changkun** [comment]
可以多开一个 terminal，或者使用 tmux 创建多个子窗口

**Comment by changkun** [comment]
Is the issue resolved?

**Comment by kvii** [comment]
No. It's just I don't want it to open.
Consider to use [service](https://pkg.go.dev/github.com/kardianos/service)?
I have used this package for my business code.

**Comment by changkun** [comment]
I think this is an essential issue that exists in the current codebase. Therefore, we should keep it open. But I am currently don't have any bandwidths to take a deep look. Hopefully, I might find some time in early Oct. I would be appreciated and be willing to take a look if you send a PR to fix this issue.
