### ISSUE TITLE
The "ws://" prefix can't be used when server's domain is not "localhost".

### ISSUE THREAD

**Issue by kvii** [changkun/midgard#23]
https://github.com/changkun/midgard/blob/8e6acdbfd6f7ef35feb5d576f4763e32cfdb1a4b/api/daemon/ws.go#L34-L39
There's no way to use 'ws://' when my server is not listening on port 443.
Have you considered to support this case?

**Comment by changkun** [comment]
I think this was a security concern. The localhost case was for local development. If we deploy the service to a server, it is necessary to use was for encryption because the service transmits clipboard content, which is usually very sensitive, such as passwords.

**Comment by kvii** [comment]
It seems that i need to learn about wss and https in the future.

**Comment by alx-xlx** [comment]
this is so restrictive, dedicating an entire server for just clipboard service. How can I run it for a domain if there are nultiple services running on the same server.

This needs to support locally shared clipboard instead of making everything go through https.

**Comment by changkun** [comment]
@alx-xlx not sure if I can understand the comments correctly. It is always ok to deploy the service via container, and adding additional router management to do whatever you want to do.
