### ISSUE TITLE
workflow failed: command not found: xdpyinfo

### ISSUE THREAD

**Issue by kvii** [changkun/midgard#25]
We should use an issue to discuss CI problem.

I copied and executed the following code  as a .sh file.
https://github.com/changkun/midgard/blob/8e6acdbfd6f7ef35feb5d576f4763e32cfdb1a4b/.github/workflows/midgard.yml#L25-L42

Then I got the same error as CI。

```
Waiting for Xvfb to be ready......  Gave up waiting for X server on :0.0
```

I copied the code of while condition(line 33), and executed it manually.

Then I got this error. I think this is the reason.

``` sh
$ xdpyinfo -display ":0.0"
zsh: command not found: xdpyinfo
```

**Comment by changkun** [comment]
Should be fixed now.
