### ISSUE TITLE
ios15 shortcut fail

### ISSUE THREAD

**Issue by qcrao** [changkun/midgard#9]

**Comment by changkun** [comment]
I found the reason. I will patch a new shortcut soon.

**Comment by changkun** [comment]
For iOS 15:

- midgard-alloc: https://www.icloud.com/shortcuts/a440412d0f12454cb4676e0ded72a9f1
- midgard-getclipboard: https://www.icloud.com/shortcuts/c88e44b318e74eedb20201e4f513dabf
- midgard-putclipboard: https://www.icloud.com/shortcuts/e875c142389e4fe6b45bbed4a517f8c8
- midgard-code2img: https://www.icloud.com/shortcuts/cec5afc61b01476e87b888163de6e39b

**Comment by changkun** [comment]
Fixed in https://github.com/changkun/midgard/commit/7e68f13ddd02843001b59665dc88cd4fbe8f7d35
